version: "3.9"
services:
  redis:
    image: redis:7.2.3-alpine
    ports:
      - "6379:6379"
    networks:
      - meterdataapplication_mynetwork
  sender-service:
    build:
      context: .
    ports:
      - "8200:8200"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
    networks:
      - meterdataapplication_mynetwork
    depends_on:
      - redis
    command: [ "sh", "-c", "sleep 10 && java -jar /app.jar" ]

networks:
  meterdataapplication_mynetwork:
    external: true