version: "3.9"
services:
  sender-service:
    build:
      context: .
    ports:
      - "8200:8200"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
    networks:
      - meterdataapplication_mynetwork
    command: [ "sh", "-c", "sleep 10 && java -jar /app.jar" ]

networks:
  meterdataapplication_mynetwork:
    external: true